# Generated by Django 4.1 on 2022-08-14 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orig_url', models.CharField(max_length=2000)),
                ('redic_url', models.CharField(max_length=2000)),
            ],
        ),
    ]
