# Generated by Django 4.1 on 2022-08-14 06:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortlink', '0003_alter_timestamp_create_dt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timestamp',
            name='create_dt',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
