# Generated by Django 4.1 on 2022-08-14 06:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortlink', '0004_alter_timestamp_create_dt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='timestamp_ptr',
        ),
        migrations.AddField(
            model_name='sample',
            name='create_dt',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='sample',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Timestamp',
        ),
    ]
