# Generated by Django 4.1 on 2022-08-14 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortlink', '0005_remove_sample_timestamp_ptr_sample_create_dt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='create_dt',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
