# Generated by Django 4.1 on 2022-08-15 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0002_remove_user_date_joined_remove_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timestamp',
            name='create_dt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
