# Generated by Django 4.1 on 2022-08-16 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0004_remove_user_timestamp_ptr_user_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Period',
            field=models.DateField(blank=True, null=True),
        ),
    ]
