# Generated by Django 4.1 on 2022-08-22 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0005_alter_user_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Url_cnt',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
