# Generated by Django 4.1 on 2022-08-22 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0006_user_url_cnt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Url_cnt',
        ),
    ]
